### ISSUE TITLE
Unable to open export zip: /export.zip is not a zip file

### ISSUE THREAD

**Issue by navgo456** [k0rventen/apple-health-grafana#16]
Get the following error even though export.zip is clearly a zip file.

[+] Running 1/0
 ✔ Container apple-health-grafana-ingester-1  Created                                                                                                  0.0s
Attaching to apple-health-grafana-ingester-1
apple-health-grafana-ingester-1  | Unzipping the export file...
apple-health-grafana-ingester-1  | Unable to open export zip: /export.zip is not a zip file
apple-health-grafana-ingester-1 exited with code 1

**Comment by k0rventen** [comment]
Hi, could you paste the content of the `docker-compose.yml` ?

**Comment by navgo456** [comment]
`version: "3"
services:
  grafana:
    image: grafana/grafana:9.5.5
    ports:
    - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=health
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/dashs/specific-metrics.json
    volumes:
    - ./provisioning:/etc/grafana/provisioning
  influx:
    image: influxdb:1.8
    restart: always
    environment:
      - INFLUXDB_DB=health
    volumes:
    - influx-data:/var/lib/influxdb
  ingester:
    image: k0rventen/apple-health-grafana-ingester
    build: ./ingester
    volumes:
    - /Desktop/export.zip:/export.zip

volumes:
  influx-data:`

**Comment by navgo456** [comment]
version: "3"
services:
  grafana:
    image: grafana/grafana:9.5.5
    ports:
    - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=health
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/dashs/specific-metrics.json
    volumes:
    - ./provisioning:/etc/grafana/provisioning
  influx:
    image: influxdb:1.8
    restart: always
    environment:
      - INFLUXDB_DB=health
    volumes:
    - influx-data:/var/lib/influxdb
  ingester:
    image: k0rventen/apple-health-grafana-ingester
    build: ./ingester
    volumes:
    - /Desktop/export.zip:/export.zip

volumes:
  influx-data:

**Comment by k0rventen** [comment]
Are you sure that  `/Desktop/export.zip` is a valid absolute path ? Depending on your OS, this should prefixed by either `/home/<user>` on linux, `/Users/<user>` on macOS or `C:\` on Windows.

**Comment by navgo456** [comment]
I did what you said and it worked. Thank you!
