### ISSUE TITLE
Shortcuts data source

### ISSUE THREAD

**Issue by MarshalX** [k0rventen/apple-health-grafana#26]
It looks like "Apple Health" and "Apple health specific metrics" dashboards are not support data from "Shortcuts" app. Could it be fixed/improved? 

Personally i have a lot data from shortcuts. I automated data import from external APIs to Apple Health, logging UV index when going outside, and simple shortcuts for logging body measurements. 

Thank you!

**Comment by k0rventen** [comment]
This is because the list of possible source 'device' is defined by:
```
show tag values from StepCount with key=device
```
So the source "Shortcuts" exists but probably not in this measurement, meaning it won't show up in the source list.

I guess I'll have to create a dedicated set() of all sources as a new measurement and use that for this variable.

**Comment by MarshalX** [comment]
ive tried main branch. works great!

**Comment by k0rventen** [comment]
Great, I'll push a new release today with these changes included.

**Comment by k0rventen** [comment]
new behavior that resolve this issue available on release [v0.3.0](https://github.com/k0rventen/apple-health-grafana/releases/tag/v0.3.0) !

**Comment by MarshalX** [comment]
Thank you!
