### ISSUE TITLE
Numbers don't match. Example: steps count per day

### ISSUE THREAD

**Issue by metawops** [k0rventen/apple-health-grafana#7]
I just imported all my health data successfully. 😊 

However, something seems to be not quite right with the numbers. 🤔 

Here's a screenshot of the "steps per day" graph from the preset Grafana dashboard "Apple health specific metrics" where I added screenshots from the Fitness App that shows the steps data from three days. 

<img width="1594" alt="Screenshot 2023-04-30 at 22 15 18" src="https://user-images.githubusercontent.com/376090/235374995-c4f542b0-d187-4083-b56f-bc6cc9a2cb73.png">

The steps curve in the Grafana dashboard always shows much higher values. – Why?

**Comment by k0rventen** [comment]
Hey, I think I figured it out. 

For some metrics, both the iPhone and the watch are creating records at roughly the same time. That can lead to multiple entries for the same activity.

I guess Apple has some kind of logic for detecting such case, so they don't add up both informations. But I didn't, so for the number of steps, the number of km walked, both of your devices counts were added up, meaning around double the correct value. 

I updated the ingester to differentiate multiple sources, and the dashboards can show this info as well. Here is an example where both my iPhone and watch are counting my steps, therefore the total was completely off.

<img width="741" alt="Screenshot 2023-05-01 at 11 33 33" src="https://user-images.githubusercontent.com/49311792/235435613-7badfd0b-90e5-4491-8fe2-211886c8a83e.png">

I tweaked the dashboards on the `Apple health specific metrics` dashboard to show the average value of all series, meaning you should have a more realistic graph now. 

I just pushed ba60f8b; to update, `git pull` the repo to grab the new dashboard then `docker compose down`/`docker compose pull`/`docker compose up` !

**Comment by metawops** [comment]
Very interesting! Much better numbers now! 👍 
The question remains, though, what number the Fitness app reports and how/if we can get that exact same number of steps for a day from Grafana ... 😳

**Comment by k0rventen** [comment]
I checked the numbers from my export, and it seems that for most of the walk/run/steps data, both the Health app and Fitness app  is reporting data only from my watch.
I guess the iPhone data is only used to fill the blanks when you're not wearing the watch ? 

To produce the same results on Grafana, you can select only your watch as the "source" variable. That seems to give me the right amount of steps:

<img width="247" alt="Screenshot 2023-05-01 at 13 13 25" src="https://user-images.githubusercontent.com/49311792/235444499-718a6286-ce4d-4700-986c-20170131dc38.png">
