### ISSUE TITLE
no export.xml file found, skipping

### ISSUE THREAD

**Issue by GeraldPape** [k0rventen/apple-health-grafana#8]
There seems a problem finding the Export.xml file in the zip file if running on Docker Windows.
The filename in my export ist written with first letter upper case: Export.xml 
```

apple-health-grafana-ingester-1  | opening Route 2022-07-21 9:11am
apple-health-grafana-ingester-1  | opening Route 2022-08-30 7:58am
apple-health-grafana-ingester-1  | opening Route 2022-08-08 9:30pm
apple-health-grafana-ingester-1  | opening Route 2022-08-01 8:20am
apple-health-grafana-ingester-1  | no export.xml file found, skipping
apple-health-grafana-ingester-1  | All done ! You can now check grafana.
```

**Comment by GeraldPape** [comment]
Did repackage the export.zip and did a lower case export.xml, now it imports the data. However, Apple Export has the **E**xport.xml eith upper case.

**Comment by k0rventen** [comment]
That's weird, are you using docker desktop for windows or docker through WSL ? 

On Linux/macOS the filename is lowercase, so that behaviour is windows specific. I'll have to try that but I do not have a windows box on hand.

**Comment by dbluxo** [comment]
Hey @k0rventen 👋 , first of all thanks for this project, I love it!

I just had the same problem on macOS 13.4.1, I also had to unpack it, lowercase it and compress it again, then it worked.
Maybe it's because my Apple Health (iOS) is in German? Maybe you could look for export.xml or Export.xml in the code?

**Comment by k0rventen** [comment]
Hi ! 
Glad you find it useful ! 

I haven't had the time to dig more on the issue, but you're right, I'll just search without case sensitivity. I should have time to do it today, will update this issue accordingly !

**Comment by k0rventen** [comment]
Hey @GeraldPape & @dbluxo 

I've released [v.0.0.4](https://github.com/k0rventen/apple-health-grafana/releases/tag/v0.0.4), which includes a fix for this issue. 
Thx for reporting it !
